[book]
authors = ["jtriley.eth"]
language = "en"
multilingual = false
src = "src"
title = "Smart Types"
description = "A document about the Smart Types library"

[output.html]
git-repository-url = "https://github.com/jtriley-eth/smart-types"
default-theme = "ayu"
additional-js = ["src/static/solidity.min.js"]